spring:
  profiles: dev
  # 终端彩色输出信息
  output.ansi.enabled: ALWAYS
  resources:
    # 不映射工程中的静态资源文件比如1：html、css
    # 如果某些情况需要映射
    # 比如 swagger2，可以在 addResourceHandlers 和 addViewControllers 中特别添加，参考 WebMvcConfig
    add-mappings: false
  mvc:
    # 当出现 404 错误时，直接抛出异常（默认是显示一个错误页面）
    throw-exception-if-no-handler-found: true
  freemarker:
    # 关闭模版检查
    checkTemplateLocation: false
  aop:
    proxy-target-class: true
    auto: true
  # 数据源（应该全部加密）
  datasource:
    druid:
      db1:
        # 连接，注意各个配置，尤其是要一次性执行多条 SQL 时，要 allowMultiQueries=true
        url: jdbc:mysql://127.0.0.1/cat_admin1?useUnicode=true&useSSL=false&allowMultiQueries=true&characterEncoding=utf-8&useLegacyDatetimeCode=false&serverTimezone=UTC
        # 用户名 root
        username: root
        # 密码 root
        password: root
        # 驱动类
        driver-class-name: com.mysql.cj.jdbc.Driver
        #druid
        type: com.alibaba.druid.pool.DruidDataSource
        initialSize: 5
        minIdle: 5
        maxActive: 20
      db2:
        url: jdbc:mysql://127.0.0.1/cat_admin1?useUnicode=true&useSSL=false&allowMultiQueries=true&characterEncoding=utf-8&useLegacyDatetimeCode=false&serverTimezone=UTC
        # 用户名 root
        username: root
        # 密码 root
        password: root
        # 驱动类
        driver-class-name: com.mysql.cj.jdbc.Driver
        #druid
        type: com.alibaba.druid.pool.DruidDataSource
        initialSize: 5
        minIdle: 5
        maxActive: 20
  # redis
  redis:
    #数据库索引（默认为0）
    #database: 0
    #服务器地址
    #host: 121.89.193.223
    #服务器连接端口
    #port: 7001
    cluster:
      nodes:
        - 192.168.1.4:7001
        - 192.168.1.4:7002
        - 192.168.1.4:7003
        - 192.168.1.4:7004
        - 192.168.1.4:7005
        - 192.168.1.4:7006
    #服务器连接密码（默认为空）
    password:
    #连接超时时间（毫秒）
    timeout: 5000
    # password:
    pool:
      #连接池中的最小空闲连接
      minIdle: 1
      #连接池中的最大空闲连接
      maxIdle: 10
      #连接池最大阻塞等待时间（使用负值表示没有限制）
      maxWait: 3
      #连接池最大连接数（使用负值表示没有限制）
      maxActive: 200

server:
  port: 8081

#mybatis-plus:
#  #外部化xml配置
#  #config-location: classpath:mybatis-config.xml
#  #指定外部化 MyBatis Properties 配置，通过该配置可以抽离配置，实现不同环境的配置部署
#  #configuration-properties: classpath:mybatis/config.properties
#  #xml扫描，多个目录用逗号或者分号分隔（告诉 Mapper 所对应的 XML 文件位置）
#  mapper-locations: classpath*:/mapper/*.xml
#  #MyBaits 别名包扫描路径，通过该属性可以给包中的类注册别名
#  type-aliases-package: com.cat.admin.modules.entity
#  #如果配置了该属性，则仅仅会扫描路径下以该类作为父类的域对象
#  #type-aliases-super-type: java.lang.Object
#  #枚举类 扫描路径，如果配置了该属性，会将路径下的枚举类进行注入，让实体类字段能够简单快捷的使用枚举属性
#  #type-enums-package: com.baomidou.mybatisplus.samples.quickstart.enums
#  #项目启动会检查xml配置存在(只在开发时候打开)
#  check-config-location: true
#  #SIMPLE：该执行器类型不做特殊的事情，为每个语句的执行创建一个新的预处理语句,REUSE：该执行器类型会复用预处理语句,BATCH：该执行器类型会批量执行所有的更新语句
#  default-executor-type: REUSE
#  configuration:
#    # 是否开启自动驼峰命名规则（camel case）映射，即从经典数据库列名 A_COLUMN（下划线命名） 到经典 Java 属性名 aColumn（驼峰命名） 的类似映射
#    map-underscore-to-camel-case: true
#    # 全局地开启或关闭配置文件中的所有映射器已经配置的任何缓存，默认为 true
#    cache-enabled: false
#    #懒加载
#    #aggressive-lazy-loading: true
#    #NONE：不启用自动映射 PARTIAL：只对非嵌套的 resultMap 进行自动映射 FULL：对所有的 resultMap 都进行自动映射
#    #auto-mapping-behavior: partial
#    #NONE：不做任何处理 (默认值)WARNING：以日志的形式打印相关警告信息 FAILING：当作映射失败处理，并抛出异常和详细信息
#    #auto-mapping-unknown-column-behavior: none
#    #如果查询结果中包含空值的列，则 MyBatis 在映射的时候，不会映射这个字段
#    call-setters-on-nulls: true
#    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  global-config:
#    db-config:
#      #表名下划线命名默认true
#      table-underline: true
#      #id类型
#      id-type: auto
#      #是否开启大写命名，默认不开启
#      #capital-mode: false
#      #逻辑已删除值,(逻辑删除下有效) 需要注入逻辑策略LogicSqlInjector 以@Bean方式注入
#      logic-not-delete-value: 0
#      #逻辑未删除值,(逻辑删除下有效)
#      logic-delete-value: 1
#      #数据库类型
#      db-type: mysql

logging.level:
    com.cat.admin.modules.mapper: debug
jwt:
  secret: secret
  expiration: 7200000
  token: Authorization

cat:
  swagger:
    title: 测试项目demo接口文档
    description: 测试项目demo接口文档
    version: 1.0.0
    termsOfServiceUrl:
    contactName:
    contactUrl:
    contactEmail:
    license:
    licenseUrl:
  #安全认证
  auth:
    # token过期时间（分钟）
    tokenExpireTime: 60
    # 用户选择保存登录状态对应token过期时间（天）
    saveLoginTime: 7
    # 限制用户登陆错误次数（次）
    loginTimeLimit: 10
    # 错误超过次数后多少分钟后才能继续登录（分钟）
    loginAfterTime: 10
    ignoreUrls:
      - /login
      - /api/system/user/getCurrentUserInfo
      - /index
      - /logout
      - /swagger-ui.html
      #      - /swagger-resources/**
      - /swagger-resources/configuration/ui
      - /swagger-resources
      - /v2/api-docs
      - /swagger-resources/configuration/security
      #      - /swagger/**
      #      - /**/v2/api-docs
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico